import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'on-primary': '#ffffff',
                'soft-mauve': '#9B859D',
                'secondary-container': '#f4daf5',
                'tertiary-fixed': '#caead7',
                'aura-rose': '#D4A5A5',
                'on-background': '#1e1b1b',
                'secondary-fixed-dim': '#d7bfd9',
                'primary-container': '#d4a5a5',
                'neural-mint': '#2ECC71',
                'deep-charcoal': '#2D3436',
                secondary: '#6c586e',
                'inverse-surface': '#342f2f',
                'surface-variant': '#e9e0e0',
                'logic-amber': '#FFBF00',
                'on-secondary-container': '#725e74',
                'primary-fixed-dim': '#ecbbba',
                'on-surface-variant': '#504444',
                primary: '#7b5455',
                'on-tertiary-fixed': '#042015',
                'on-primary-fixed-variant': '#603d3e',
                'on-error': '#ffffff',
                'on-secondary-fixed': '#251629',
                'on-secondary': '#ffffff',
                'on-tertiary-container': '#2d493b',
                'surface-container-low': '#fbf1f1',
                'on-tertiary-fixed-variant': '#314d3e',
                'secondary-fixed': '#f4daf5',
                'inverse-primary': '#ecbbba',
                'surface-container-high': '#efe6e5',
                'surface-dim': '#e1d8d7',
                tertiary: '#486555',
                background: '#fff8f7',
                'surface-tint': '#7b5455',
                'on-surface': '#1e1b1b',
                'surface-container-highest': '#e9e0e0',
                surface: '#fff8f7',
                'on-primary-container': '#5d3a3b',
                'outline-variant': '#d4c2c2',
                'surface-bright': '#fff8f7',
                'on-tertiary': '#ffffff',
                'surface-container-lowest': '#ffffff',
                error: '#ba1a1a',
                'primary-fixed': '#ffdad9',
                'tertiary-container': '#99b8a6',
                'on-secondary-fixed-variant': '#534156',
                'on-primary-fixed': '#2f1314',
                'surface-container': '#f5eceb',
                'on-error-container': '#93000a',
                'inverse-on-surface': '#f8efee',
                'mist-white': '#F7F7F7',
                'error-container': '#ffdad6',
                outline: '#827473',
                'tertiary-fixed-dim': '#aecebb',
                hairline: '#E2E2E2',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                sm: '8px',
                md: '16px',
                gutter: '24px',
                unit: '4px',
                margin: '32px',
                xxl: '64px',
                lg: '24px',
                xl: '40px',
                xs: '4px',
            },
            fontFamily: {
                code: ['monospace', 'sans-serif'],
                'label-caps': ['Inter', 'system-ui', 'sans-serif'],
                'body-lg': ['Inter', 'system-ui', 'sans-serif'],
                h3: ['Inter', 'system-ui', 'sans-serif'],
                h1: ['Inter', 'system-ui', 'sans-serif'],
                h2: ['Inter', 'system-ui', 'sans-serif'],
                display: ['Inter', 'system-ui', 'sans-serif'],
                'body-sm': ['Inter', 'system-ui', 'sans-serif'],
                'body-md': ['Inter', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                code: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
                'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
                h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
                h1: ['32px', { lineHeight: '1.25', fontWeight: '600' }],
                h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
                display: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
            },
        },
    },
    plugins: [forms],
};
